int8    field1
uint8   field2
int16   field3
uint16  field4
int32   field5
uint32  field6
int64   field7
uint64  field8
float32 field9
float64 field10
string  field11

int8[]    afield1
uint8[]   afield2
int16[]   afield3
uint16[]  afield4
int32[]   afield5
uint32[]  afield6
int64[]   afield7
uint64[]  afield8
float32[] afield9
float64[] afield10
string[]  afield11

geometry_msgs/Vector3 cfield1
geometry_msgs/Vector3[] cfield2
